### ISSUE TITLE
android 8.1支持

### ISSUE THREAD

**Issue by edsion1107** [codeskyblue/stf-binaries#2]
https://github.com/codeskyblue/stf-binaries/raw/master/node_modules/minicap-prebuilt/prebuilt/arm64-v8a/lib/android-27/minicap.so

这个链接404了，应该是minicap缺少android 8.1的预编译版本吧

**Comment by codeskyblue** [comment]
我只是minicap的搬运工，并不负责编译。可以去minicap的主页去提issue

**Comment by codeskyblue** [comment]
支持了，不用等了
